name: Check for Updates

on:
  schedule:
    - cron: "58 5 * * *"
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  TARGET_TAG: latest

jobs:
  version-check:
    name: Compare Local and Upstream Versions
    runs-on: ubuntu-24.04
    permissions: write-all
    outputs:
      update_required: ${{ steps.compare_version_hashes.outputs.update_required }}
      current_version: ${{ steps.get_release_version.outputs.current_version }}
      upstream_version: ${{ steps.get_upstream_version.outputs.upstream_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Load current version
        uses: actions/cache/restore@v5
        with:
          key: current_version
          path: current_version_file
          fail-on-cache-miss: false

      - name: Get current version hash
        id: get_current_version_hash
        run: |
          set -e
          echo "Getting current version hash"
          if [ -f current_version_file ]; then
            CURRENT_VERSION_HASH=$(cat current_version_file)
          else
            CURRENT_VERSION="no-version"
          fi
          echo "Current version hash: $CURRENT_VERSION_HASH" >> $GITHUB_STEP_SUMMARY
          echo "current_version_hash=$CURRENT_VERSION_HASH" >> $GITHUB_OUTPUT

      - name: Download upstream target tag info
        run: |
          wget -q "https://hub.docker.com/v2/repositories/library/mediawiki/tags/${{ env.TARGET_TAG }}" -O "${{ env.TARGET_TAG }}.json"

      - name: Get upstream version hash
        id: get_upstream_version_hash
        run: |
          set -e
          echo "Getting upstream version hash for ${{ env.TARGET_TAG }}"
          UPSTREAM_VERSION_HASH=$(jq '.digest' "${{ env.TARGET_TAG }}.json")
          # The `current_version_file` has already been read by now
          echo -n $UPSTREAM_VERSION_HASH > current_version_file
          echo "upstream_version_hash=$UPSTREAM_VERSION_HASH" >> $GITHUB_OUTPUT
          echo "Upstream hash: $UPSTREAM_VERSION_HASH" >> $GITHUB_STEP_SUMMARY

      - name: Compare version hashes
        id: compare_version_hashes
        env:
          CURRENT_VERSION_HASH: ${{ steps.get_current_version_hash.outputs.current_version_hash }}
          UPSTREAM_VERSION_HASH: ${{ steps.get_upstream_version_hash.outputs.upstream_version_hash }}
        run: |
          set -e
          if [ "$UPSTREAM_VERSION_HASH" == "$CURRENT_VERSION_HASH" ]; then
              echo "Current version $CURRENT_VERSION_HASH is equal to Upstream version $UPSTREAM_VERSION_HASH."
              echo "No update required." >> $GITHUB_STEP_SUMMARY
              echo "update_required=false" >> $GITHUB_OUTPUT
          else
              echo "Upstream version $UPSTREAM_VERSION_HASH is different from the Current version $CURRENT_VERSION_HASH."
              echo "Creating release... :rocket:" >> $GITHUB_STEP_SUMMARY
              echo "update_required=true" >> $GITHUB_OUTPUT
          fi

      - name: Download the repo manifest
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        run: |
          wget -q "https://github.com/docker-library/official-images/raw/refs/heads/master/library/mediawiki" -O manifest.txt

      - name: Get upstream tag aliases for target tag
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        id: get_upstream_tags
        run: |
          set -e
          echo "Getting upstream tag aliases for ${{ env.TARGET_TAG }}"
          TARGET_TAGS="$(grep '^Tags:' | sed 's/$/, /'  manifest.txt | grep ' '${{ env.TARGET_TAG }}',' | sed 's/^Tags: *//;s/, $//')"
          echo "Found tags for ${{ env.TARGET_TAG }}: $TARGET_TAGS"
          echo "target_tags=${TARGET_TAGS}" >> $GITHUB_OUTPUT
          TARGET_TAGS_JSON='["'$(echo $ALL_TAGS | sed 's/, $//;s/, /", "/g')'"]'
          echo "target_tags_json=$TARGET_TAGS_JSON" >> $GITHUB_OUTPUT
          echo "Alias tags for ${{ env.TARGET_TAG }}: $TARGET_TAGS" >> $GITHUB_STEP_SUMMARY

      - name: Get upstream full version number
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        id: get_upstream_full_version
        env:
          TARGET_TAGS: ${{ steps.get_upstream_tags.outputs.target_tags }}
        run: |
          set -e
          echo "Getting full upstream version number"
          FULL_VERSION=$(echo $TARGET_TAGS | sed 's/, /\n/g' | grep '^[0-9]\+\.[0-9]\+\.[0-9]\+$')
          echo "full_version=$FULL_VERSION" >> $GITHUB_OUTPUT
          echo "Upstream full version number: $FULL_VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Get upstream extension version number part
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        id: get_upstream_extension_version
        env:
          FULL_VERSION: ${{ steps.get_upstream_full_version.outputs.full_version }}
        run: |
          set -e
          echo "Getting upstream extension version"
          EXTENSION_VERSION=$(echo $FULL_VERSION | sed 's/^\([0-9]\+\.[0-9]\+\).*/\1/' | sed 's/\./_/g')
          echo "extension_version=REL$EXTENSION_VERSION" >> $GITHUB_OUTPUT
          echo "Extension version: REL$EXTENSION_VERSION" >> $GITHUB_STEP_SUMMARY


      # Set up QEMU for cross-platform builds
      - name: Set up QEMU
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        uses: docker/setup-buildx-action@v3.12.0
        uses: docker/setup-buildx-action@v3.11.1

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        uses: docker/login-action@v3.7.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        id: meta
        uses: docker/metadata-action@v5.10.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=auto
          tags: |-
            ${{ join(fromJSON(steps.get_upstream_tags.outputs.target_tags_json), '
            ') }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        if: ${{ steps.compare_version_hashes.outputs.update_required == 'true' }}
        id: build-and-push
        uses: docker/build-push-action@v6
        env:
          VERSION: ${{ steps.get_upstream_full_version.outputs.full_version }}
          EXTENSION_BRANCH: ${{ steps.get_upstream_extension_version.outputs.extension_version }}
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ steps.get_upstream_full_version.outputs.full_version }}
            EXTENSION_BRANCH=${{ steps.get_upstream_extension_version.outputs.extension_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Cache new current version hash
        uses: actions/cache/save@v4
        with:
          key: current_version
          path: current_version_file

